variables:
  NOMAD_VAR_HOSTNAMES: '["wbm-exclusion-helper.crawl1.archive.org"]'
  NOMAD_VAR_METRICS: "false"
  NOMAD_VAR_CHECK_PROTOCOL: "http"
  NOMAD_VAR_CHECK_PATH: "/"
  NOMAD_VAR_FORCE_PULL: "true"
  NOMAD_VAR_CPU: 2000
  NOMAD_VAR_MEMORY: 2000
  NOMAD_VAR_COUNT: 1
  NOMAD_VAR_PORTS: '{8501 = "http"}'

include:
  - project: "wb/crawl-nomad/pipeline-toolbox"
    ref: master
    file: "nomad-build-and-deploy.yml"
